import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>B2GSOFT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        
      </div>

    </>
  )
}


